insert into MEASUREMENT (ID, SENSOR_ID, VALUE, TIMESTAMP) values (1, 1, 65.05,CURRENT_TIMESTAMP);
insert into MEASUREMENT (ID, SENSOR_ID, VALUE, TIMESTAMP) values (2, 1, 88.92, CURRENT_TIMESTAMP);
insert into MEASUREMENT (ID, SENSOR_ID, VALUE, TIMESTAMP) values (3, 1, 106.44, CURRENT_TIMESTAMP);
insert into MEASUREMENT (ID, SENSOR_ID, VALUE, TIMESTAMP) values (4, 2, 44.55,CURRENT_TIMESTAMP);
insert into MEASUREMENT (ID, SENSOR_ID, VALUE, TIMESTAMP) values (5, 2, 25.92, CURRENT_TIMESTAMP);
insert into MEASUREMENT (ID, SENSOR_ID, VALUE, TIMESTAMP) values (6, 2, 136.44, CURRENT_TIMESTAMP);
insert into MEASUREMENT (ID, SENSOR_ID, VALUE, TIMESTAMP) values (7, 2, 77.28, CURRENT_TIMESTAMP);