CREATE TABLE MEASUREMENT_MEDIAN (
  ID               IDENTITY PRIMARY KEY,
  SENSOR_ID        BIGINT    NOT NULL,
  MEDIAN_VALUE     DECIMAL   NOT NULL,
  MEDIAN_TIMESTAMP TIMESTAMP NOT NULL,
  CONSTRAINT FK_MEASUREMENT_MEDIAN_SENSOR_ID FOREIGN KEY (SENSOR_ID) REFERENCES SENSOR (ID)
);